### ISSUE TITLE
Does this work on shared memory?

### ISSUE THREAD

**Issue by Jerry-Ma** [rigtorp/MPMCQueue#16]
For example, Linux `open_shm`, or `MPI_win_allocate_shared`, combined with placement new:

```
const int N = 10; // capacity
std::byte* buffer;
/* allocate buffer as shm on main proc*/
if (/*main proc*/) {
    new (buffer) MPMCQueue<int> q(N);
    // consume
} else {
    new (buffer) MPMCQueue<int> q(N);
   // produce
}
```

**Comment by rigtorp** [comment]
Not out of the box, but the changes needed to make it work are small. The
constructor calls malloc to allocate memory for the data. You need to
replace that with a call to allocate shared memory. I have been thinking
about adding support for custom allocators.

**Comment by Jerry-Ma** [comment]
I am quite new to the concept of lock free, so the use of atomic operations behind the scene will just work for shared memory pointers, right?

I know that for example std::mutex does not work in IPC context, but boost::interprocess::mutex works. This is why I had this question.

**Comment by rigtorp** [comment]
Not necessarily. It's only guaranteed for main memory, not mapped device
memory. If you are using non temporal reads and stores you might also need
to additional code to deal with that.

This queue algorithm will work with mmaped main memory.

**Comment by rigtorp** [comment]
@Jerry-Ma Latest version of MPMCQueue now supports custom allocators. You should be able to use a custom allocator in order to use shared memory.
