### ISSUE TITLE
Why T can not be std::function<void()>?

### ISSUE THREAD

**Issue by valaxkong** [rigtorp/MPMCQueue#22]
My Compiler is gcc 5.4.
The static_assert is raised when compile this code : MPMCQueue<std::function<void()>>
What did this happen? For my knowledge, std::function is no-throw move assignment, so it should not trigger the static_assert in your code.

**Comment by rigtorp** [comment]
std::function is not noexcept assignable:
https://en.cppreference.com/w/cpp/utility/functional/function/operator%3D

You can make a custom one that is nonexcept movable. The functors
destructor would have to be noexcept.
