### ISSUE TITLE
Compile errors

### ISSUE THREAD

**Issue by peddycoart** [rigtorp/MPMCQueue#23]
Using GNU g++  4.8.5/Centos 7, I get the following compile errors when trying to compile a fresh clone of MPMCQueue.  Can you offer assistance?

MPMCQueue.h:264:56: error: missing binary operator before token "("
 #if defined(__has_cpp_attribute) && __has_cpp_attribute(no_unique_address)
MPMCQueue.h:58:13: error: ‘bad_array_new_length’ is not a member of ‘std’
       throw std::bad_array_new_length();

**Comment by peddycoart** [comment]
I get the same errors when trying to build SPSCQueue.  I assume it is on my end.  gcc 4.8.5 is supposed to be C+11 compliant, so I am not sure what the issue may be.

**Comment by rigtorp** [comment]
I haven't tested on such an old compiler and do not plan on supporting it. Should be easy for you to fix those errors.
