### ISSUE TITLE
push_front ?

### ISSUE THREAD

**Issue by cdemez** [rigtorp/MPMCQueue#3]
Hi,

Is there a way to have a push_front (instead of a push_back) ?

**Comment by rigtorp** [comment]
I guess you want a lock-free stack. There should be implementations of this available.

**Comment by cdemez** [comment]
Thanks for your answer,

But no, I need both push_back and push_front, like we found in std:vector etc ... !

**Comment by rigtorp** [comment]
I'm not aware of a lock free datastructure that supports that. Never ran
into the problem. Check out this paper:
http://www.cs.rochester.edu/~scott/papers/1996_PODC_queues.pdf might give
you some hints.
