### ISSUE TITLE
Resolve construction core dump 

### ISSUE THREAD

**Issue by g302ge** [rigtorp/MPMCQueue#39]
if some class constructor cause some nullptr exception caused core dump. How to resolve this at 

https://github.com/rigtorp/MPMCQueue/blob/28d05c021d68fc5280b593329d1982ed02f9d7b3/include/rigtorp/MPMCQueue.h#L173

**Comment by rigtorp** [comment]
Constructors must be noexcept:
static_assert(std::is_nothrow_constructible<T, Args &&...>::value,
                  "T must be nothrow constructible with Args&&...");

**Comment by g302ge** [comment]
Thx for your reply. But in my view, the constructor must not be noexcept is a very strong safety for the lock free situation. In other words the constructor or some code in the critical section like constructor in this case should be more atomic as they can do. if this view is correct ?

**Comment by rigtorp** [comment]
There is no way to unwind a partial enqueue operation unfortunately. This
means that constructing the enqeued time cannot fail.

The solution is to mark failed enques and skip them, I didn't want everyone
to pay the cost of this by default. What you can do is create a wrapper
type:
template <typename T>
struct nothrow_wrapper {
  T v;
  bool valid;

  nothrow_wrapper(T &&v) {
    try {
       this->v = v;
       valid=true;
    catch (...) {
       valid=false;
     }
  }
}

And then check for valid items when you pop();

However it should always be possible to create a noexcept move constructor.

**Comment by g302ge** [comment]
thx for your reply , I have fix my variant version in a safe situation
