### ISSUE TITLE
BUG: can't Push if head_ overflow?

### ISSUE THREAD

**Issue by esrrhs** [rigtorp/MPMCQueue#40]
I read the code, and found if the head_ overflow, then it can't Push anymore.
and I change the head_ type from size_t to uint16_t, and just run code:
```
MPMCQueue<size_t> mp(1024);
for (size_t i = 0; i < UINT64_MAX; ++i) {
    mp.push(i);
    size_t j = 0;
    if (!mp.try_pop(j)) {
        std::cout << "failed " << i << std::endl;
        break;
    }
    std::cout << "success " << i << std::endl;
}
```
and then it stop cout at 65535 and then dead
```
success 65533
success 65534
success 65535
```

**Comment by esrrhs** [comment]
so if I use the queue a long time, the size_t will has the same problem. or this is just ok? because the time may be very long?

**Comment by esrrhs** [comment]
I run a test at my computer, found there will be thousand of years to make the size_t overflow. okay, I should not consider that situation :)

**Comment by rigtorp** [comment]
Yeah, the idea is that the 64 bit counter is huge and will never overflow.
You bring up a good point, it would be nice to find a way to cleanly handle
the overflow.
