### ISSUE TITLE
Std::map to queue

### ISSUE THREAD

**Issue by vswdigitall** [rigtorp/MPMCQueue#42]
Hi, can i emplace/push std::map object?

**Comment by brmarkus** [comment]
Depends on the data-structure you use for std::map's template parameter - could your data be moved and emplaced?

**Comment by vswdigitall** [comment]
It is std::map< size_t, int32_t >.

**Comment by brmarkus** [comment]
Should be no problem for such basic data types.

**Comment by vswdigitall** [comment]
std::pair int int works.
Thank you.

**Comment by brmarkus** [comment]
`std::pair` instead of `std::map` - have you found problems with `std::map` so that you redesigned your data structure?

**Comment by vswdigitall** [comment]
Yes, redesigned. My mistake.

**Comment by brmarkus** [comment]
No worries.
Feel free to close this Github issue if no more questions, see "https://docs.github.com/en/issues/tracking-your-work-with-issues/closing-an-issue".
