### ISSUE TITLE
Feature request: is LIFO possible?

### ISSUE THREAD

**Issue by emmenlau** [rigtorp/MPMCQueue#5]
This is a very nice MPMC queue! Is it possible to add LIFO functionality? It looks as if `pop()` could be modified to use `head_.fetch_sub(1)` but I am uncertain if this breaks something?

**Comment by rigtorp** [comment]
Someone else asked about this recently.

I believe it's possible, but needs some changes that would reduce
throughput for FIFO case. So would be best to create separate class for
this.

**Comment by emmenlau** [comment]
Could you help to implement this? Your experience in this topic would be great.
