### ISSUE TITLE
ssize_t is not present in Visual Studio 2017

### ISSUE THREAD

**Issue by ikde** [rigtorp/MPMCQueue#8]
ssize_t is a posix extension, and is not present in Visual Studio 2017.
Can it be fixed?

**Comment by rigtorp** [comment]
Yes you just need to update this assert https://github.com/rigtorp/MPMCQueue/blob/c7ee1820427bbf28c1f5ea196c725d12feb8b4b6/include/rigtorp/MPMCQueue.h#L72

PR welcome!
