### ISSUE TITLE
How is this queue lock-free?

### ISSUE THREAD

**Issue by WonderfulVoid** [rigtorp/MPMCQueue#9]
A thread that blocks after the call to fetch_add() will block later producers and consumers that use the same slot. As objects are enqueued (and dequeued), the ring will wrap around and come back to earlier slots. For enqueue, such an event can be pushed far into the future as the queue capacity can be made arbitrarily large (as memory allows) but not for dequeue. Possibly blocking could be avoided if producers and consumers synchronise with each other (e.g. use CAS to update the slot and restart the operation (allocate new index) if the slot doesn't have the expected value.

**Comment by rigtorp** [comment]
If you use blocking pop then consumers will indeed block until the producer
has produced.

With this queue acquiring a producer slot (fetch_add) is the FIFO barrier.
A blocking consumer will block until the next producer has produced.

If you want to reduce the FIFO guarantees you could do that by using a SPSC
queue per thread.

But in the end it is lockfree since the suspended producer can make
progress independently of any other thread. It just needs to be scheduled.
There is no deadlock possible.

So again it is lockfree but not wait free.

**Comment by WonderfulVoid** [comment]
"But in the end it is lockfree since the suspended producer can make progress independently of any other thread"
But other threads cannot indefinitely make progress if there is one blocking (producer or consumer) thread.
Do we agree on this?

**Comment by rigtorp** [comment]
What do you mean by a blocking thread?

**Comment by WonderfulVoid** [comment]
If a thread doesn't make the required progress (e.g. setting a flag, incrementing a counter) for whatever reason, it will be blocking progress for other threads when you use blocking algorithms.
There are many ways a thread can block progress temporarily or permanently; get interrupted or preempted, crash or get killed, hang (loop forever), wait for other threads, block in a system call, execute a signal handler. If this happens in the wrong place, I (informally) call this thread the blocking thread.
The way to avoid such problems is to use non-blocking (e.g. obstruction-free, lock-free, wait-free) algorithms. But if the progress of one thread depends on the progress of other threads, the algorithm is not non-blocking, it is a blocking algorithm.
If you depend on the scheduler to let a thread run and make the required progress in order for other threads to make progress, you only have a blocking algorithm. Think of how you make progress with a spin lock.

**Comment by rigtorp** [comment]
Yes, that's why I don't claim it is wait-free.

In any case I use this successfully in production daily. If you can accept less strict FIFO guarantees you can also you one SPSC queue per thread (https://github.com/rigtorp/SPSCQueue).

**Comment by WonderfulVoid** [comment]
https://stackoverflow.com/questions/45907210/lock-free-progress-guarantees

**Comment by rigtorp** [comment]
That's a great discussion! So this algorithm has lock-free enqueue and non-blocking dequeue.
